

version: "2.1"

services:
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: edx.devstack.mysql
    hostname: mysql.devstack.edx
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.6.36
    ports:
      - "3506:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
    restart: on-failure
    ports:
      - "8080:80"
    environment:
      - SERVICE_80_CHECK_TCP=true
    volumes:
      - ./fbc.py:/etc/nginx/fbc.py
    depends_on:
      - mysql

volumes:
  mysql_data:
